plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"
    - "log/**/*"
    - "tmp/**/*"
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  Width: 2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Max: 30
  Exclude:
    - "spec/**/*"
    - "config/**/*"

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Rails/I18nLocaleTexts:
  Enabled: false

